script:
  - wp plugin delete hello || true
  - wp plugin delete akismet || true
  - wp theme delete twentytwenty || true
  - wp theme delete twentytwentyone || true
  - wp theme delete twentytwentytwo || true
  - wp theme delete twentytwentythree || true
  - wp rewrite structure '/%category%/%postname%/'
  - composer plugins:activate

web:
  host: test.wp.devit.ovh

ftp:
  enabled: true

pvc:
  enabled: true

volumes:
  html:
    hostPath: null
    emptyDir: null
    persistentVolumeClaim:
      claimName: '{{ include "wordpress.fullname" . }}'
