image:
  wordpress: wordpress:6.0.3-php7.4-apache
  mariadb: mariadb:10.9.3

web:
  host: http.mydev

wordpress:
  user_ini: |
    upload_max_filesize = 5000M
    post_max_size = 5000M
    cgi.fix_pathinfo = 0
    memory_limit = 128M

  mpm_prefork_conf: |
    # StartServers: number of server processes to start
    # MinSpareServers: minimum number of server processes which are kept spare
    # MaxSpareServers: maximum number of server processes which are kept spare
    # MaxRequestWorkers: maximum number of server processes allowed to start
    # MaxConnectionsPerChild: maximum number of requests a server process serves
    <IfModule mpm_prefork_module>
      StartServers		6
      MinSpareServers	2
      MaxSpareServers	6
      MaxRequestWorkers	64
      MaxConnectionsPerChild  16
    </IfModule>

database:
  user: "example"
  password: "example"
  name: "example"
  rootPassword: "example"
  config: |
    [mysqld]
    # default_authentication_plugin=mysql_native_password
    skip-host-cache
    skip-name-resolve

    # copied for  testing from https://dba.stackexchange.com/questions/64055/how-to-reduce-mysql-memory-used

    innodb_buffer_pool_size=5M
    innodb_log_buffer_size=256K
    query_cache_size=0
    max_connections=10
    key_buffer_size=8
    thread_cache_size=0
    host_cache_size=0
    innodb_ft_cache_size=1600000
    innodb_ft_total_cache_size=32000000

    # per thread or per operation settings
    # this crashes mariadb
    #thread_stack=131072
    sort_buffer_size=32K
    read_buffer_size=8200
    read_rnd_buffer_size=8200
    max_heap_table_size=16K
    tmp_table_size=1K
    bulk_insert_buffer_size=0
    join_buffer_size=128
    net_buffer_length=1K
    innodb_sort_buffer_size=64K

    #settings that relate to the binary log (if enabled)
    binlog_cache_size=4K
    binlog_stmt_cache_size=4K
