apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "issuer"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
#    email: user@example.com
    privateKeySecretRef:
      name: "privatekeyissuer"
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "issuer-staging"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    email: user@example.com
    privateKeySecretRef:
      name: "privatekeyissuer-staging"
    solvers:
      - http01:
          ingress:
            class: nginx