apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "wordpress.fullname" . }}-files"
data:
  {{- range $key, $value := .Values.files }}
  {{ $key }}: {{ toYaml $value.content | indent 2}}
  {{end}}
