apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "metadata.name.configmap.scripts" . }}"
data:
  {{- range $key, $value := .Values.files }}
  {{ $key }}: {{ toYaml $value.content | indent 2}}
  {{end}}
