apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "wordpress.fullname" . }}-dpl"
spec:
  selector:
    matchLabels:
      app: "{{ include "wordpress.fullname" . }}"
  template:
    metadata:
      annotations:
        checksum/files: {{ join "," .Values.files | sha256sum }}
        checksum/plugins: {{ join "," .Values.plugins | sha256sum }}
        checksum/themes: {{ join "," .Values.themes | sha256sum }}
      labels:
        app: "{{ include "wordpress.fullname" . }}"
    spec:

      volumes:
        {{- include "volumes" (dict "Values" .Values "Context" . ) }}
        {{- include "volumes.files" . }}

      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - mysql
            - wordpress
            - {{.Values.web.host}}

      containers:
      {{/*  ░█──░█ ░█▀▀▀█ ░█▀▀█ ░█▀▀▄ ░█▀▀█ ░█▀▀█ ░█▀▀▀ ░█▀▀▀█ ░█▀▀▀█*/}}
      {{/*  ░█░█░█ ░█──░█ ░█▄▄▀ ░█─░█ ░█▄▄█ ░█▄▄▀ ░█▀▀▀ ─▀▀▀▄▄ ─▀▀▀▄▄*/}}
      {{/*  ░█▄▀▄█ ░█▄▄▄█ ░█─░█ ░█▄▄▀ ░█─── ░█─░█ ░█▄▄▄ ░█▄▄▄█ ░█▄▄▄█*/}}
        - name: wordpress
          image: {{ .Values.image.wordpress }}
          ports:
            - containerPort: 80
              name: "wordpress"
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DEBUG
              value: "1"
          envFrom:
            - secretRef:
                name: "{{ include "wordpress.fullname" . }}-database"
          volumeMounts:
            {{ template "volumeMounts" (dict "Values" .Values "Container" "wordpress" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "wordpress") }}


      {{/*  ▒█▀▀▄ ░█▀▀█ ▀▀█▀▀ ░█▀▀█ ▒█▀▀█ ░█▀▀█ ▒█▀▀▀█ ▒█▀▀▀*/}}
      {{/*  ▒█░▒█ ▒█▄▄█ ░▒█░░ ▒█▄▄█ ▒█▀▀▄ ▒█▄▄█ ░▀▀▀▄▄ ▒█▀▀▀*/}}
      {{/*  ▒█▄▄▀ ▒█░▒█ ░▒█░░ ▒█░▒█ ▒█▄▄█ ▒█░▒█ ▒█▄▄▄█ ▒█▄▄▄*/}}
        - name: database
          image: {{ .Values.image.database }}
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_HOST
              value: mysql

          envFrom:
            - secretRef:
                name: "{{ include "wordpress.fullname" . }}-database"

          volumeMounts:
            {{ template "volumeMounts" (dict "Values" .Values "Container" "database" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "database") }}

      {{/*  ▒█░░▒█ ▒█▀▀█ ▒█▀▀█ ▒█░░░ ▀█▀*/}}
      {{/*  ▒█▒█▒█ ▒█▄▄█ ▒█░░░ ▒█░░░ ▒█░*/}}
      {{/*  ▒█▄▀▄█ ▒█░░░ ▒█▄▄█ ▒█▄▄█ ▄█▄*/}}
        - name: cli
          image: {{ .Values.image.wpcli }}
          imagePullPolicy: Always
          securityContext:
            runAsGroup: 33
            runAsUser: 33
          args:
            - set -eux; echo "Running Scripts" {{- range .Values.script }} && {{.}} {{- end}}
          volumeMounts:
            {{- template "volumeMounts" (dict "Values" .Values "Container" "cli" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "cli") }}

          envFrom:
            - secretRef:
                name: {{ include "wordpress.fullname" . }}-wordpress
            - secretRef:
                name: {{ include "wordpress.fullname" . }}-database

    {{/*  ▒█▀▀▀█ ▒█▀▀▀ ▀▀█▀▀ ▒█▀▀█*/}}
    {{/*  ░▀▀▀▄▄ ▒█▀▀▀ ░▒█░░ ▒█▄▄█*/}}
    {{/*  ▒█▄▄▄█ ▒█░░░ ░▒█░░ ▒█░░░*/}}
        {{ if .Values.ftp.enabled }}
        - name: sftp
          image: quay.io/wp-env/sftp:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 22
              name: "sftp"
          volumeMounts:
            {{ template "volumeMounts" (dict "Values" .Values "Container" "sftp" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "sftp") }}
          args:
            - {{.Values.ftp.login}}:{{.Values.ftp.password}}:33
        {{ end }}
