apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "wordpress.fullname" . }}-dpl"
spec:
  selector:
    matchLabels:
      app: "{{ include "wordpress.fullname" . }}"
  template:
    metadata:
      annotations:
        checksum/files: {{ join "," .Values.files | sha256sum }}
        checksum/plugins: {{ join "," .Values.plugins | sha256sum }}
        checksum/themes: {{ join "," .Values.themes | sha256sum }}
      labels:
        app: "{{ include "wordpress.fullname" . }}"
    spec:

      volumes:
        {{- include "volumes" . }}
        {{- include "volumes.files" . }}

      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - mysql
            - wordpress
            - {{.Values.web.host}}

      initContainers:

      {{/*  ▒█▀▀█ ▒█░▒█ ▒█▀▀▀█ ▒█░░▒█ ▒█▄░▒█ ▒█▀▀█ ▒█▀▀▀ ▒█▀▀█ ▒█▀▀▀█ ▒█▀▀▀█*/}}
      {{/*  ▒█░░░ ▒█▀▀█ ▒█░░▒█ ▒█▒█▒█ ▒█▒█▒█ ▒█▄▄▀ ▒█▀▀▀ ▒█▄▄█ ▒█░░▒█ ░▀▀▀▄▄*/}}
      {{/*  ▒█▄▄█ ▒█░▒█ ▒█▄▄▄█ ▒█▄▀▄█ ▒█░░▀█ ▒█░▒█ ▒█▄▄▄ ▒█░░░ ▒█▄▄▄█ ▒█▄▄▄█*/}}
        - name: chownrepos
          image: busybox
          command: [ "/bin/sh", "-c"]
          args:
            - set -eux && chown -R 1588:1588 /repos/themes /repos/plugins
          volumeMounts:
            {{ template "volumeMounts" (dict "Values" .Values "Container" "chownrepos" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "chownrepos") }}


      {{/*  ▒█▀▀█ ▀█▀ ▀▀█▀▀ ▒█▀▀█ ▒█░░░ ▒█▀▀▀█ ▒█▄░▒█ ▒█▀▀▀ ▒█▀▀█*/}}
      {{/*  ▒█░▄▄ ▒█░ ░▒█░░ ▒█░░░ ▒█░░░ ▒█░░▒█ ▒█▒█▒█ ▒█▀▀▀ ▒█▄▄▀*/}}
      {{/*  ▒█▄▄█ ▄█▄ ░▒█░░ ▒█▄▄█ ▒█▄▄█ ▒█▄▄▄█ ▒█░░▀█ ▒█▄▄▄ ▒█░▒█*/}}
        - name: gitcloner
          image: bukowa/test:gitcloner
          securityContext:
            runAsGroup: 1588
            runAsUser: 1588
          imagePullPolicy: Always
          volumeMounts:
            {{ template "volumeMounts" (dict "Values" .Values "Container" "gitcloner" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "gitcloner") }}
          args:
            - https://gitlab.com/bukowa/gitcloner-repotest-submodule

      containers:
      {{/*  ░█──░█ ░█▀▀▀█ ░█▀▀█ ░█▀▀▄ ░█▀▀█ ░█▀▀█ ░█▀▀▀ ░█▀▀▀█ ░█▀▀▀█*/}}
      {{/*  ░█░█░█ ░█──░█ ░█▄▄▀ ░█─░█ ░█▄▄█ ░█▄▄▀ ░█▀▀▀ ─▀▀▀▄▄ ─▀▀▀▄▄*/}}
      {{/*  ░█▄▀▄█ ░█▄▄▄█ ░█─░█ ░█▄▄▀ ░█─── ░█─░█ ░█▄▄▄ ░█▄▄▄█ ░█▄▄▄█*/}}
        - name: wordpress
          image: {{ .Values.image.wordpress }}
          ports:
            - containerPort: 80
              name: "wordpress"
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DEBUG
              value: "1"
          envFrom:
            - secretRef:
                name: "{{ include "wordpress.fullname" . }}-database"
          volumeMounts:
            {{ template "volumeMounts" (dict "Values" .Values "Container" "wordpress" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "wordpress") }}


      {{/*  ▒█▀▀▄ ░█▀▀█ ▀▀█▀▀ ░█▀▀█ ▒█▀▀█ ░█▀▀█ ▒█▀▀▀█ ▒█▀▀▀*/}}
      {{/*  ▒█░▒█ ▒█▄▄█ ░▒█░░ ▒█▄▄█ ▒█▀▀▄ ▒█▄▄█ ░▀▀▀▄▄ ▒█▀▀▀*/}}
      {{/*  ▒█▄▄▀ ▒█░▒█ ░▒█░░ ▒█░▒█ ▒█▄▄█ ▒█░▒█ ▒█▄▄▄█ ▒█▄▄▄*/}}
        - name: database
          image: {{ .Values.image.database }}
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_HOST
              value: mysql

          envFrom:
            - secretRef:
                name: "{{ include "wordpress.fullname" . }}-database"

          volumeMounts:
            {{ template "volumeMounts" (dict "Values" .Values "Container" "database" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "database") }}

      {{/*  ▒█░░▒█ ▒█▀▀█ ▒█▀▀█ ▒█░░░ ▀█▀*/}}
      {{/*  ▒█▒█▒█ ▒█▄▄█ ▒█░░░ ▒█░░░ ▒█░*/}}
      {{/*  ▒█▄▀▄█ ▒█░░░ ▒█▄▄█ ▒█▄▄█ ▄█▄*/}}
        - name: cli
          image: wordpress:cli-php7.4
          imagePullPolicy: Always
          securityContext:
            runAsGroup: 33
            runAsUser: 33
          command:
            - /bin/bash
            - -c
            - |
              set -eux
              /scripts/wait-for-entrypoint.sh -t 30 {{ .Values.web.url }}/wp-admin/install.php
              if ! wp core is-installed;
              then
              echo "Executing wordpress_install scripts"
              {{- range .Values.wordpress_install }}
                {{.}}
              {{- end}}
              fi
              echo "Executing wordpress_start scripts"
              {{- range .Values.wordpress_start }}
                {{.}}
              {{- end }}
              {{ range .Values.plugins }} wp plugin install --activate {{.}} &&
              {{- end}}
              {{ range .Values.themes }} wp theme install --activate {{.}} &&
              {{- end }} sleep infinity

          volumeMounts:
            {{- template "volumeMounts" (dict "Values" .Values "Container" "cli" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "cli") }}

          envFrom:
            - secretRef:
                name: {{ include "wordpress.fullname" . }}-wordpress
            - secretRef:
                name: {{ include "wordpress.fullname" . }}-database

    {{/*  ▒█▀▀▀█ ▒█▀▀▀ ▀▀█▀▀ ▒█▀▀█*/}}
    {{/*  ░▀▀▀▄▄ ▒█▀▀▀ ░▒█░░ ▒█▄▄█*/}}
    {{/*  ▒█▄▄▄█ ▒█░░░ ░▒█░░ ▒█░░░*/}}
        {{ if .Values.ftp.enabled }}
        - name: sftp
          image: quay.io/wp-env/sftp:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 22
              name: "sftp"
          volumeMounts:
            {{- template "volumeMounts" (dict "Values" .Values "Container" "sftp" "Context" . )}}
            {{- template "volumeMounts.files" (dict "Values" .Values "Container" "sftp") }}
          args:
            - {{.Values.ftp.login}}:{{.Values.ftp.password}}:33
        {{ end }}
