apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-database"
stringData:
  WORDPRESS_DB_USER: "{{.Values.database.user}}"
  WORDPRESS_DB_PASSWORD: "{{.Values.database.password}}"
  WORDPRESS_DB_NAME: "{{.Values.database.name}}"
  MYSQL_ROOT_PASSWORD: "{{.Values.database.rootPassword}}"
  MYSQL_DATABASE: "{{.Values.database.name}}"
  MYSQL_USER: "{{.Values.database.user}}"
  MYSQL_PASSWORD: "{{.Values.database.password}}"
  MARIADB_PASSWORD: "{{.Values.database.password}}"
  MARIADB_ROOT_PASSWORD: "{{.Values.database.rootPassword}}"
  MARIADB_DATABASE: "{{.Values.database.name}}"
  MARIADB_USER: "{{.Values.database.user}}"
