apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wordpress
stringData:
    WORDPRESS_PORT: "80"
    WORDPRESS_ADDRESS: "wordpress:80"
    WORDPRESS_URL: "{{.Values.web.url}}"
    WORDPRESS_TITLE: "title"
    WORDPRESS_LOGIN: "title"
    WORDPRESS_PASSWORD: "title"
    WORDPRESS_EMAIL: "example@example.com"