apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
spec:
  selector:
    app: {{ include "wordpress.fullname" . }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: "http"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wordpress.fullname" . }}
spec:
  rules:
    - host: {{ .Values.web.host }}
      http:
        paths:
          - backend:
              service:
                port:
                  name: "http"
                name: {{ include "wordpress.fullname" . }}
            pathType: Prefix
            path: /
